import express from "express";
import { upload } from "../middlewares/upload.multer.js";
import { createShop, getShopdetails, updateShopDetails, updateShopStatus, deleteShop } from "../controllers/seller/Shop.js";
import { authenticate } from "../middlewares/auth.middleware.js";
import { SellerVerification, updateVerificationIdCard } from "../controllers/seller/SellerVerification.js";
import { productDetails, productPricing, productcategory, productPromotion, FetchSellerListings, EditSellerListing, DeleteSellerListing, PauseSellerListing, activeListing, BoostPlans, planPrice, createBoostAd, fetchBoostAd } from '../controllers/seller/Listing.js';
import { createComment, getCommentsByProduct } from '../controllers/seller/listing.comment.js';
import { getNotifications } from '../controllers/seller/Notification.js';

const router = express.Router();

router.post("/create/shop", authenticate, upload.single("file"), createShop);
router.get("/shop/details", authenticate, getShopdetails);
router.post("/seller/vefication", authenticate, upload.fields([{ name: "idCard", maxCount: 1}, {name: "passport", maxCount: 1}]), SellerVerification);
router.post("/update/seller/vefication", authenticate, upload.fields([{ name: "idCard", maxCount: 1}]), updateVerificationIdCard);
router.put('/listing/pause', authenticate, PauseSellerListing);
router.get("/notifications", authenticate, getNotifications);
router.post("/comments", authenticate, createComment);
router.put('/update/product/promotion', authenticate, productPromotion);
router.put('/update/product/category', authenticate, productcategory);
router.put('/update/product/pricing', authenticate, productPricing);
router.put("/update/shop", authenticate, upload.single('file'), updateShopDetails);
router.get("/seller/listing", authenticate, FetchSellerListings);
router.get('/active/listing', authenticate, activeListing);
router.get('/boost/plans', authenticate, BoostPlans);
router.post('/boost/ads', authenticate, createBoostAd);
router.get('/boost/ads', authenticate, fetchBoostAd);
router.get('/plan/price', authenticate, planPrice);
router.delete('/shop/delete', authenticate, deleteShop);
router.put("/shop/status/update", authenticate, updateShopStatus);
router.post('/create/product/:shopId', authenticate, upload.fields([{ name: 'productImage', maxCount: 1}, { name: "productReel", maxCount: 1}]), productDetails);
router.put("/update/listing/:productId", authenticate, EditSellerListing);
router.delete("/delete/listing/:productId", authenticate, DeleteSellerListing);
router.get("/comments/product/:productId", getCommentsByProduct);
export default router;